CREATE OR REPLACE PROCEDURE ATL_PRECO_MAT_STAGING IS

	CURSOR WCUR IS
		SELECT	TRIM(COD_ANTIGO)	ITM,
				TRIM(CENTRO_ERP)	FILIAL
		FROM	STAGING_MATERIAL;
	REC WCUR %ROWTYPE;

	PRC_PDR	staging_material.prec_padr_erp%TYPE;

BEGIN
	OPEN WCUR;
	FETCH WCUR INTO REC;

	LOOP
		EXIT WHEN WCUR%NOTFOUND;

		BEGIN
			SELECT	((SUM(INCUMA) +
					 SUM(INAN01) +
					 SUM(INAN02) +
					 SUM(INAN03) +
					 SUM(INAN04) +
					 SUM(INAN05) +
					 SUM(INAN06) +
					 SUM(INAN07) +
					 SUM(INAN08) +
					 SUM(INAN09) +
					 SUM(INAN10) +
					 SUM(INAN11) +
					 SUM(INAN12))/100) /
					((SUM(INCMQT) +
					 SUM(INNQ01) +
					 SUM(INNQ02) +
					 SUM(INNQ03) +
					 SUM(INNQ04) +
					 SUM(INNQ05) +
					 SUM(INNQ06) +
					 SUM(INNQ07) +
					 SUM(INNQ08) +
					 SUM(INNQ09) +
					 SUM(INNQ10) +
					 SUM(INNQ11) +
					 SUM(INNQ12))/10000)
			INTO	PRC_PDR
			FROM	F41112_TONE
			WHERE	TO_CHAR(INITM) = REC.ITM
			AND		TRIM(INMCU) = REC.FILIAL
			AND		INFY = TO_CHAR(SYSDATE,'YY')
			AND		INCTRY = 20;

			BEGIN
				UPDATE	STAGING_MATERIAL
				SET		PREC_PADR_ERP = PRC_PDR,
						PREC_PADR_SAN = PRC_PDR
				WHERE	TRIM(COD_ANTIGO) = REC.ITM
				AND		TRIM(CENTRO_ERP) = REC.FILIAL;

				COMMIT;

			EXCEPTION
				WHEN OTHERS THEN
					DBMS_OUTPUT.PUT_LINE('ERRO UPDATE; COD_ANTIGO = '||REC.ITM||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
					NULL;
			END;

		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				BEGIN
					UPDATE	STAGING_MATERIAL
					SET		PREC_PADR_ERP = 0,
							PREC_PADR_SAN = 0
					WHERE	TRIM(COD_ANTIGO) = REC.ITM
					AND		TRIM(CENTRO_ERP) = REC.FILIAL;

					COMMIT;

				EXCEPTION
					WHEN OTHERS THEN
						DBMS_OUTPUT.PUT_LINE('ERRO UPDATE; COD_ANTIGO = '||REC.ITM||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
					NULL;
				END;

			WHEN ZERO_DIVIDE THEN
				BEGIN
					UPDATE	STAGING_MATERIAL
					SET		PREC_PADR_ERP = 0,
							PREC_PADR_SAN = 0
					WHERE	TRIM(COD_ANTIGO) = REC.ITM
					AND		TRIM(CENTRO_ERP) = REC.FILIAL;

					COMMIT;

				EXCEPTION
					WHEN OTHERS THEN
						DBMS_OUTPUT.PUT_LINE('ERRO UPDATE; COD_ANTIGO = '||REC.ITM||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
					NULL;
				END;

			WHEN OTHERS THEN
				DBMS_OUTPUT.PUT_LINE('ERRO SELECT; COD_ANTIGO = '||REC.ITM||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
				NULL;
		END;

		FETCH WCUR INTO REC;
	END LOOP;
	CLOSE WCUR;
	COMMIT;
END;