CREATE OR REPLACE PROCEDURE STAGING_EXTRAI_CAR IS

	CURSOR WCUR IS
		SELECT	TRIM(NUM_DOC)																		NUM_DOC,
				MAX(NVL(TRIM("USER"), ' '))															USERNAME,
				MAX(NVL(TRIM(DT_DOC), ' '))															DT_DOC,
				MAX(NVL(TRIM(TP_DOC), ' '))															TP_DOC,
				MAX(NVL(TRIM(EMP1), ' '))															EMP,
				MAX(NVL(TRIM(DT_LAN), ' '))															DT_LAN,
				MAX(NVL(TRIM(EXE), ' '))															EXE,
				MAX(NVL(TRIM("REF"), ' '))															REFERENCIA,
				MAX(NVL(TRIM(TXT_H), ' '))															TXT_H,
				MAX(NVL(TRIM(CC), ' '))																CC,
				MAX(NVL(TRIM(TXT2), ' '))															TEXTO_G,
				MAX(NVL(TRIM(MOEDA), ' '))															MOEDA,
				CASE WHEN SUM(VAL_BR) > 0 THEN
					LTRIM(REPLACE(TO_CHAR((SUM(VAL_BR)),'9999999999999990.00'),'.',','))||'-'
				ELSE
					LTRIM(REPLACE(TO_CHAR((-1*SUM(VAL_BR)),'9999999999999990.00'),'.',','))
				END                                         										VAL_BR
		FROM	STAGING_CAR
		WHERE	STATUS = 'L'
		GROUP BY TRIM(NUM_DOC);
	REC WCUR %ROWTYPE;

	CURSOR WCUR1 IS
		SELECT	NVL(TRIM(COD_CLI), ' ')															COD_CLI,
				NVL(TRIM(EMP2), ' ')															EMP2,
				NVL(TRIM(COD_RZ), ' ')															COD_RZ,
				NVL(TRIM(DT_VEN), ' ')															DT_VEN,
				NVL(TRIM(FORM_PG), ' ')															FPAG,
				NVL(TRIM(ATR1), ' ')															ATRIB,
				NVL(TRIM(TXT1), ' ')															TEXTO,
				NVL(TRIM(BANCO), ' ')															BANCO,
				NVL(TRIM(ID_CNAB), ' ')															ID_CNAB,
				NVL(TRIM(NN), ' ')																NN,
				TRIM(PARCELA)																	PARCELA,
				LTRIM(REPLACE(TO_CHAR(NVL(VL_LAN_IT1, 0),'9999999999999990.00'),'.',','))		VALOR_PARCELA
		FROM	STAGING_CAR
		WHERE	TRIM(NUM_DOC) = REC.NUM_DOC
		ORDER BY NUM_DOC,PARCELA;
	REC1 WCUR1 %ROWTYPE;

	I			INTEGER;
	V_SEQ		INTEGER;
	V_SEQ1		INTEGER;
	V_SEQ2		INTEGER;
	LINHA_H		VARCHAR2(1000);
	LINHA_R		VARCHAR2(1000);
	LINHA_G		VARCHAR2(1000);
	LINHA_A		VARCHAR2(1000);
	V_ARQUIVO	UTL_FILE.FILE_TYPE;
	W_ARQUIVO	VARCHAR2(50);
	C_DIRET		VARCHAR2(60);

BEGIN

	V_SEQ := 0;
	V_SEQ1 := 0;
	V_SEQ2 := 0;
	W_ARQUIVO := 'DSAPCAR'||TO_CHAR(SYSDATE,'YYMMDDHH24MISS')||'.TXT';
	C_DIRET := 'EXT_CAP_CAR';

	OPEN WCUR;

	LOOP
		FETCH WCUR INTO REC;
		EXIT WHEN WCUR%NOTFOUND;

		--ABRE ARQUIVO
		BEGIN
			V_ARQUIVO := UTL_FILE.FOPEN(C_DIRET, W_ARQUIVO, 'W');
		EXCEPTION
			WHEN UTL_FILE.INVALID_OPERATION THEN
				DBMS_OUTPUT.PUT_LINE('ERRO AO ABRIR O DIRETORIO-ARQUIVO = '||C_DIRET||'-'||W_ARQUIVO||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
				NULL;
		END;

		V_SEQ := V_SEQ + 1;

		--INSERE DOCUMENTHEADER (H)
		LINHA_H := LPAD(V_SEQ,8,0)||';H;'||REC.USERNAME||';'||REC.DT_DOC||';'||REC.TP_DOC||';'||REC.EMP||';'||REC.DT_LAN||';'||REC.EXE||';'||REC.REFERENCIA||';'||REC.TXT_H;
		UTL_FILE.put_line(V_ARQUIVO,LINHA_H);

		--INSERE ACCOUNTRECEIVABLE (R)
		OPEN WCUR1;

		LOOP
			FETCH WCUR1 INTO REC1;
			EXIT WHEN WCUR1%NOTFOUND;

			V_SEQ1 := V_SEQ1 + 1;
			LINHA_R := LPAD(V_SEQ,8,0)||';R;'||LPAD(V_SEQ1,8,0)||';'||REC1.COD_CLI||';'||REC1.EMP2||';'||REC1.COD_RZ||';'||REC1.DT_VEN||';'||REC1.FPAG||';'||REC1.ATRIB||';'||REC1.TEXTO||';'||REC1.BANCO||';'||REC1.ID_CNAB||';'||REC1.NN;
			UTL_FILE.put_line(V_ARQUIVO,LINHA_R);

		END LOOP;
		CLOSE WCUR1;

		--INSERE ACCOUNTGL (G)
		V_SEQ2 := V_SEQ1 + 1;
		LINHA_G := LPAD(V_SEQ,8,0)||';G;'||LPAD(V_SEQ2,8,0)||';'||REC.CC||';'||REC.TEXTO_G||';'||REC.EMP||';Carga Saldo Clientes';
		UTL_FILE.put_line(V_ARQUIVO,LINHA_G);
		V_SEQ1 := 0;

		--INSERE CURRENCYAMOUNT(A)
		OPEN WCUR1;

		LOOP
			FETCH WCUR1 INTO REC1;
			EXIT WHEN WCUR1%NOTFOUND;
			V_SEQ1 := V_SEQ1 + 1;
			LINHA_A := LPAD(V_SEQ,8,0)||';A;'||LPAD(V_SEQ1,8,0)||';'||REC.MOEDA||';'||REC1.VALOR_PARCELA;
			UTL_FILE.put_line(V_ARQUIVO,LINHA_A);

		END LOOP;
		CLOSE WCUR1;

		--INSERE LINHA FALTANTE DE CURRENCYAMOUNT(A)
		LINHA_A := LPAD(V_SEQ,8,0)||';A;'||LPAD(V_SEQ2,8,0)||';'||REC.MOEDA||';'||REC.VAL_BR;
		UTL_FILE.put_line(V_ARQUIVO,LINHA_A);
		V_SEQ1 := 0;
		V_SEQ2 := 0;
	END LOOP;

	CLOSE WCUR;

	--FECHA ARQUIVO
	UTL_FILE.FCLOSE(V_ARQUIVO);
END;
