CREATE OR REPLACE PROCEDURE STAGING_MILTIPLUS_BP IS

	CURSOR CLIENTE IS
		SELECT	TRIM(CODIGO_ANTIGO)								AS CODIGO,
				TRIM(TRIM(NOME_1_SAN)||' '||TRIM(NOME_2_SAN))	AS NOME, 
				NVL(TRIM(CNPJ_SAN),'-')							AS CNPJ,
				NVL(TRIM(CPF_SAN),'-')							AS CPF,
				CASE TRIM(STATUS)
					WHEN TRANSLATE ('L' USING NCHAR_CS) THEN 'Liberado para Migrar'
					WHEN TRANSLATE ('P' USING NCHAR_CS) THEN 'Pendente'
					WHEN TRANSLATE ('E' USING NCHAR_CS) THEN 'Em andamento'
				END  																AS STATUS
		FROM   STAGING_FORNECEDOR_CLIENTE A
		WHERE  STATUS = 'L'
		AND    TIPO_CADASTRO = 'C';
	RECCLI CLIENTE %ROWTYPE;
	
	CURSOR OUTROS_CNPJ IS
		SELECT	TRIM(CODIGO_ANTIGO)													AS CODIGO,
				TRIM(TRIM(NOME_1_SAN)||' '||TRIM(NOME_2_SAN))						AS NOME,
				NVL(TRIM(CNPJ_SAN),'1')												AS CNPJ,
				NVL(TRIM(CPF_SAN),'1')												AS CPF,
				CASE TRIM(TIPO_CADASTRO)
					WHEN TRANSLATE ('C' USING NCHAR_CS) THEN 'CLIENTE'
					WHEN TRANSLATE ('V' USING NCHAR_CS) THEN 'FORNECEDOR'
					WHEN TRANSLATE ('T' USING NCHAR_CS) THEN 'TRANSPORTADOR CIF'
					WHEN TRANSLATE ('TB' USING NCHAR_CS) THEN 'TRANSPORTADOR FOB'
					WHEN TRANSLATE ('E' USING NCHAR_CS) THEN 'FUNCIONÁRIO'
					WHEN TRANSLATE ('MT' USING NCHAR_CS) THEN 'MOTORISTA'
				END 																AS TIPO_CADASTRO,
				CASE TRIM(STATUS)
					WHEN TRANSLATE ('L' USING NCHAR_CS) THEN 'Liberado para Migrar'
					WHEN TRANSLATE ('P' USING NCHAR_CS) THEN 'Pendente'
					WHEN TRANSLATE ('E' USING NCHAR_CS) THEN 'Em andamento'
				END  																AS STATUS
		FROM	STAGING_FORNECEDOR_CLIENTE
		WHERE	TRIM(CNPJ_SAN) = RECCLI.CNPJ
		AND		TRIM(CODIGO_ANTIGO) <> RECCLI.CODIGO
		AND		STATUS NOT IN ('N','O')
		AND		TIPO_CADASTRO <> 'CE';
	RECCNPJ OUTROS_CNPJ %ROWTYPE;
	
	CURSOR OUTROS_CPF IS
		SELECT	TRIM(CODIGO_ANTIGO)													AS CODIGO,
				TRIM(TRIM(NOME_1_SAN)||' '||TRIM(NOME_2_SAN))						AS NOME,
				NVL(TRIM(CNPJ_SAN),'1')												AS CNPJ,
				NVL(TRIM(CPF_SAN),'1')												AS CPF,
				CASE TRIM(TIPO_CADASTRO)
					WHEN TRANSLATE ('C' USING NCHAR_CS) THEN 'CLIENTE'
					WHEN TRANSLATE ('V' USING NCHAR_CS) THEN 'FORNECEDOR'
					WHEN TRANSLATE ('T' USING NCHAR_CS) THEN 'TRANSPORTADOR CIF'
					WHEN TRANSLATE ('TB' USING NCHAR_CS) THEN 'TRANSPORTADOR FOB'
					WHEN TRANSLATE ('E' USING NCHAR_CS) THEN 'FUNCIONÁRIO'
					WHEN TRANSLATE ('MT' USING NCHAR_CS) THEN 'MOTORISTA'
				END 																AS TIPO_CADASTRO,
				CASE TRIM(STATUS)
					WHEN TRANSLATE ('L' USING NCHAR_CS) THEN 'Liberado para Migrar'
					WHEN TRANSLATE ('P' USING NCHAR_CS) THEN 'Pendente'
					WHEN TRANSLATE ('E' USING NCHAR_CS) THEN 'Em andamento'
				END  																AS STATUS
		FROM	STAGING_FORNECEDOR_CLIENTE
		WHERE	TRIM(CNPJ_SAN) = RECCLI.CPF
		AND		TRIM(CODIGO_ANTIGO) <> RECCLI.CODIGO
		AND		STATUS NOT IN ('N','O')
		AND		TIPO_CADASTRO <> 'CE';
	RECCPF OUTROS_CPF %ROWTYPE;
	
	
	LINHA		VARCHAR2(1000);
	W_ARQUIVO	VARCHAR2(50);
	C_DIRET		VARCHAR2(60);
	CONTADOR	INTEGER;
	V_ARQUIVO	UTL_FILE.FILE_TYPE;

BEGIN
	W_ARQUIVO := 'MULTIPLUS BP_'||TO_CHAR(SYSDATE,'YYMMDDHH24MISS')||'.TXT';
	C_DIRET := 'EXT_CAP_CAR';
	--ABRE ARQUIVO
	BEGIN
		V_ARQUIVO := UTL_FILE.FOPEN(C_DIRET, W_ARQUIVO, 'W');
	EXCEPTION
		WHEN UTL_FILE.INVALID_OPERATION THEN
			DBMS_OUTPUT.PUT_LINE('ERRO AO ABRIR O DIRETORIO-ARQUIVO = '||C_DIRET||'-'||W_ARQUIVO||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
			NULL;
	END;
	
	OPEN CLIENTE;
	
	LOOP
		<<prox_cli>>
		FETCH CLIENTE INTO RECCLI;
		EXIT WHEN CLIENTE%NOTFOUND;
		
		SELECT	COUNT(*)
		INTO	CONTADOR
		FROM	STAGING_FORNECEDOR_CLIENTE
		WHERE	(TRIM(CNPJ_SAN) = RECCLI.CNPJ OR TRIM(CPF_SAN) = RECCLI.CPF)
		AND		TRIM(CODIGO_ANTIGO) <> RECCLI.CODIGO
		AND		STATUS NOT IN ('N','O')
		AND		TIPO_CADASTRO <> 'CE';

		IF CONTADOR >= 1 THEN
			LINHA := 'CLIENTE: '||RECCLI.NOME||' Código antigo = '||RECCLI.CODIGO||' CNPJ = '||RECCLI.CNPJ||' CPF = '||RECCLI.CPF||' Status = '||RECCLI.STATUS;
			UTL_FILE.put_line(V_ARQUIVO,LINHA);
			
			IF RECCLI.CNPJ = '-' THEN
				OPEN OUTROS_CPF;
				
				LINHA := ' ;Código Antigo;Nome;CNPJ;CPF;Tipo de Cadastro;Status';
				UTL_FILE.put_line(V_ARQUIVO,LINHA);
				
				LOOP
					FETCH OUTROS_CPF INTO RECCPF;
					EXIT WHEN OUTROS_CPF%NOTFOUND;
					
					LINHA := ' ;'||RECCPF.CODIGO||';'||RECCPF.NOME||';'||'-'||';'||RECCPF.CPF||';'||RECCPF.TIPO_CADASTRO||';'||RECCPF.STATUS;
					UTL_FILE.put_line(V_ARQUIVO,LINHA);
				END LOOP;
				
				CLOSE OUTROS_CPF;
				
				LINHA := ' ';
				UTL_FILE.put_line(V_ARQUIVO,LINHA);
			
			ELSE
				OPEN OUTROS_CNPJ;
				
				LINHA := ' ;Código Antigo;Nome;CNPJ;CPF;Tipo de Cadastro;Status';
				UTL_FILE.put_line(V_ARQUIVO,LINHA);
				
				LOOP
					FETCH OUTROS_CNPJ INTO RECCNPJ;
					EXIT WHEN OUTROS_CNPJ%NOTFOUND;
					
					LINHA := ' ;'||RECCNPJ.CODIGO||';'||RECCNPJ.NOME||';'||RECCNPJ.CNPJ||';'||'-'||';'||RECCNPJ.TIPO_CADASTRO||';'||RECCNPJ.STATUS;
					UTL_FILE.put_line(V_ARQUIVO,LINHA);
				END LOOP;
			
				CLOSE OUTROS_CNPJ;
				
				LINHA := ' ';
				UTL_FILE.put_line(V_ARQUIVO,LINHA);
			
			END IF;
		ELSE
			GOTO prox_cli;
		END IF;
	END LOOP;
	
	CLOSE CLIENTE;
	
	--FECHA ARQUIVO
	UTL_FILE.FCLOSE(V_ARQUIVO);
END;