DECLARE
	CURSOR WCUR IS
		SELECT	tipo_cadastro,
				codigo_antigo,
				agrupamento_parceiro,
				nome_1_san,
				nome_2_san,
				termo_pesquisa_1,
				termo_pesquisa_2,
				setor_industrial,
				rua_san,
				numero_san,
				complemento_san,
				bairro_san,
				cep_san,
				dom_fiscal_san,
				meso_san,
				micro_san,
				cidade_san,
				uf_san,
				pais_san,
				cont_prin_san,
				email_san email_san,
				to_char(telefone_san) telefone_san,
				to_char(celular_san) celular_san,
				fax,
				idioma,
				pessoa_fisica,
				cnpj_san,
				cpf_san,
				incricao_estadual_san,
				inscricao_municipal_san,
				cnh,
				cei_cno,
				emp,
				conta_conciliacao,
				grupo_adm_tesouraria,
				condicao_pagamento_san,
				forma_pagamento_san,
				bloqueio_pagamento,
				moeda_san,
				chave_banco_san,
				conta_bancaria_san,
				chave_controle_san,
				to_char(cod_categoria_irf) cod_categoria_irf,
				incoterms,
				zona_transporte,
				revisao_faturas_base_entra601b,
				categoria_cfop_cliente,
				codigo_suframa,
				cnae,
				natureza_juridica,
				numero_crt,
				contribuinte_icms,
				tp_prin_set_ind,
				org_vendas,
				canal_distribuicao_san,
				setor_atividade,
				grupo_preco_san,
				lista_preco,
				escritorio_vendas,
				grupo_vendedores,
				ec,
				centro_fornecedor,
				condicao_expediacao,
				fornecimento_completo,
				remessa_parcial_item,
				grp_clas_cont_cliente,
				classificacao_fiscal,
				to_char(fp) fp,
				status,
				status_1,
				status_2,
				status_3,
				to_char(info) info,
				to_char(observacao) observacao,
				to_char(info_cart) info_cart
		FROM	BP_BKP;
	REC WCUR %ROWTYPE;
	
BEGIN
	OPEN WCUR;
	LOOP
		FETCH WCUR INTO REC;
		EXIT WHEN WCUR%NOTFOUND;
		
		BEGIN
			UPDATE	STAGING_FORNECEDOR_CLIENTE 
			SET	agrupamento_parceiro         	= REC.agrupamento_parceiro,
				nome_1_san             			= REC.nome_1_san,
				nome_2_san             			= REC.nome_2_san,
				termo_pesquisa_1           		= REC.termo_pesquisa_1,
				termo_pesquisa_2           		= REC.termo_pesquisa_2,
				setor_industrial				= REC.setor_industrial,
				rua_san                        	= REC.rua_san,
				numero_san                     	= REC.numero_san,
				complemento_san                	= REC.complemento_san,
				bairro_san                     	= REC.bairro_san,
				cep_san                        	= REC.cep_san,
				dom_fiscal_san                 	= REC.dom_fiscal_san,
				meso_san                       	= REC.meso_san,
				micro_san                      	= REC.micro_san,
				cidade_san                     	= REC.cidade_san,
				uf_san                         	= REC.uf_san,
				pais_san                       	= REC.pais_san,
				cont_prin_san                  	= REC.cont_prin_san,
				email_san                      	= REC.email_san,
				telefone_san                   	= REC.telefone_san,
				celular_san                    	= REC.celular_san,
				fax                            	= REC.fax,
				idioma                         	= REC.idioma,
				pessoa_fisica                  	= REC.pessoa_fisica,
				cnpj_san                       	= REC.cnpj_san,
				cpf_san                        	= REC.cpf_san,
				incricao_estadual_san          	= REC.incricao_estadual_san,
				inscricao_municipal_san        	= REC.inscricao_municipal_san,
				cnh                            	= REC.cnh,
				cei_cno                        	= REC.cei_cno,
				emp                            	= REC.emp,
				conta_conciliacao              	= REC.conta_conciliacao,
				grupo_adm_tesouraria           	= REC.grupo_adm_tesouraria,
				condicao_pagamento_san         	= REC.condicao_pagamento_san,
				forma_pagamento_san            	= REC.forma_pagamento_san,
				bloqueio_pagamento             	= REC.bloqueio_pagamento,
				moeda_san                      	= REC.moeda_san,
				chave_banco_san                	= REC.chave_banco_san,
				conta_bancaria_san             	= REC.conta_bancaria_san,
				chave_controle_san             	= REC.chave_controle_san,
				cod_categoria_irf              	= REC.cod_categoria_irf,
				incoterms						= REC.incoterms,
				zona_transporte					= REC.zona_transporte,
				revisao_faturas_base_entra601b	= REC.revisao_faturas_base_entra601b,
				categoria_cfop_cliente          = REC.categoria_cfop_cliente,
				codigo_suframa                  = REC.codigo_suframa,
				cnae                            = REC.cnae,
				natureza_juridica               = REC.natureza_juridica,
				numero_crt                      = REC.numero_crt,
				contribuinte_icms               = REC.contribuinte_icms,
				tp_prin_set_ind                 = REC.tp_prin_set_ind,
				org_vendas                      = REC.org_vendas,
				canal_distribuicao_san          = REC.canal_distribuicao_san,
				setor_atividade                 = REC.setor_atividade,
				grupo_preco_san                 = REC.grupo_preco_san,
				lista_preco                     = REC.lista_preco,
				escritorio_vendas               = REC.escritorio_vendas,
				grupo_vendedores                = REC.grupo_vendedores,
				ec                              = REC.ec,
				centro_fornecedor               = REC.centro_fornecedor,
				condicao_expediacao             = REC.condicao_expediacao,
				fornecimento_completo           = REC.fornecimento_completo,
				remessa_parcial_item            = REC.remessa_parcial_item,
				grp_clas_cont_cliente           = REC.grp_clas_cont_cliente,
				classificacao_fiscal            = REC.classificacao_fiscal,
				fp                              = REC.fp,
				status                          = REC.status,
				status_1                        = REC.status_1,
				status_2                        = REC.status_2,
				status_3						= REC.status_3,
				info                            = REC.info,
				observacao                      = REC.observacao,
				info_cart                       = REC.info_cart
			WHERE	CODIGO_ANTIGO = REC.codigo_antigo  
			AND		TIPO_CADASTRO = REC.TIPO_CADASTRO;
			
			COMMIT;
			
		EXCEPTION
			WHEN OTHERS THEN
				DBMS_OUTPUT.PUT_LINE('ERRO NO CODIGO ANTIGO: '||REC.codigo_antigo||'; Erro Oracle: ' || TO_CHAR(SQLCODE)||'-'|| SQLERRM);
				NULL;
		END;
	END LOOP;
	
	CLOSE WCUR;
	COMMIT;
	
END;