----TRIGGER CONTROLA ULTIMA DATA DE INSERT/UPDATE DO LIMITE DE CRÉDITO
CREATE OR REPLACE TRIGGER LC_SAP_IU_TR
	BEFORE INSERT OR UPDATE ON STAGING_LIMITE_CREDITO FOR EACH ROW
BEGIN
	--ATUALIZA DATA DE INSERT/UPDATE
	:NEW.STATUS_5 := TO_CHAR(SYSDATE,'DD-MON-YYYY HH24:MI:SS');
END;
/