--TRIGGER CONTROLA ULTIMA DATA DE INSERT/UPDATE DA INFRAÇÂO
CREATE OR REPLACE TRIGGER IF_SAP_IU_TR
	BEFORE INSERT OR UPDATE ON STAGING_INFRACOES FOR EACH ROW
BEGIN
	--ATUALIZA DATA DE INSERT/UPDATE
	:NEW.STATUS_5 := TO_CHAR(SYSDATE,'DD-MON-YYYY HH24:MI:SS');
END;
/